@startuml server-registry-interactions
hide footbox

' You can style participants globally if you want
skinparam participant {
  BackgroundColor #DAE8FC
  BorderColor #000000
  FontColor #1e293b
  FontSize 18
  FontStyle light
  RoundCorner 10
}

skinparam sequenceActorFontSize 18

skinparam ParticipantBorderThickness 2
skinparam ParticipantPadding 10

skinparam BoxFontSize 30
skinparam BoxPadding 25

skinparam backgroundColor #FFFFFF

' If you want to use a custom actor sprite, you must define it as a sprite (see previous answer).
actor "NetOps\nEngineer" as NetOps

box "Network Data Catalog" #FCFCFC
  participant "Server\nRegistry" as ServerRegistry
  participant "Knowledge Graph\nDatabase" as KGDB
end box

box "Network Device" #LightBlue
  participant "NETCONF\nServer" as NETCONF
  participant "gNMI\nServer" as gNMI
end box

NetOps -> ServerRegistry : (1) POST Register\nnetwork device
ServerRegistry --> NetOps

ServerRegistry -> KGDB : (2) SPARQL UPDATE KG\nPlatform Module
KGDB --> ServerRegistry

ServerRegistry -> NETCONF : (3) NETCONF Get ietf-netconf-monitoring
NETCONF --> ServerRegistry

ServerRegistry -> KGDB : (4) SPARQL UPDATE KG\nServer Module
KGDB --> ServerRegistry

ServerRegistry -> NETCONF : (5) NETCONF Get ietf-yang-library
NETCONF --> ServerRegistry

ServerRegistry -> KGDB : (6) SPARQL UPDATE KG\nServer Module & Library Module
KGDB --> ServerRegistry

opt gNMI Server
ServerRegistry -> gNMI : (7) gNMI Get Capabilities
gNMI --> ServerRegistry

ServerRegistry -> KGDB : (8) SPARQL UPDATE KG\nServer Module
KGDB --> ServerRegistry
end
@enduml
