openapi: 3.0.3
info:
  title: Server Registry API
  version: "1.0.0"
  description: API to register devices with network management protocols.
servers:
  - url: "http://localhost:80"

paths:
  /devices:
    post:
      summary: Register a device
      operationId: registerDevice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceRegistry'
      responses:
        '201':
          description: Device registered successfully
        '400':
          description: Invalid request

components:
  schemas:
    DeviceRegistry:
      type: object
      required:
        - device_id
        - platform
        - os_name
        - os_version
        - vendor
      properties:
        device_id:
          type: string
          description: "Network device ID"
          example: srl
        platform:
          type: string
          description: "Name of network platform"
          example: "7250 XR"
        os_name:
          type: string
          description: "Operating system name"
          example: "SR Linux"
        os_version:
          type: string
          description: "Operating system version"
          example: "24.10"
        vendor:
          type: string
          example: nokia
        gnmi:
          $ref: '#/components/schemas/ProtocolConfig'
        netconf:
          $ref: '#/components/schemas/ProtocolConfig'

    ProtocolConfig:
      type: object
      required:
        - address
        - port
        - credentials
      properties:
        address:
          type: string
          format: ipv4
          description: "IP address of the network device"
          example: "172.100.100.11"
        port:
          type: integer
          description: "Port where YANG server can be reached"
          example: 57400
        credentials:
          $ref: '#/components/schemas/Credentials'

    Credentials:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          example: admin
        password:
          type: string
          example: NokiaSrl1!
